# Uncomment the next line to define a global platform for your project
platform :ios, '6.0'

target 'MTXKit-Demo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for MTXKit-Demo
  pod 'MTXKit'

  target 'MTXKit-DemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MTXKit-DemoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
